#!/usr/bin/env node
/**
 * codegen.mjs — Generate typed TypeScript exports from exported artifact JSONs.
 *
 * Reads artifacts/*.json (produced by export-artifacts.js) and generates:
 *   generated/artifacts.ts — typed contract constants
 *   generated/index.ts     — barrel export
 *
 * Also computes keccak256 init code hash for UniswapV2Pair and writes
 * generated/_init-code-hash.ts.
 */

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const artifactsDir = join(__dirname, "..", "artifacts");
const generatedDir = join(__dirname, "..", "generated");

mkdirSync(generatedDir, { recursive: true });

// ── Read all artifact JSONs ────────────────────────────────────────────────

const files = readdirSync(artifactsDir)
	.filter((f) => f.endsWith(".json") && !f.startsWith("_"))
	.sort();

const lines = [
	"// Auto-generated by scripts/codegen.mjs — DO NOT EDIT",
	"",
	"export interface ContractArtifact {",
	"  readonly contractName: string;",
	"  readonly abi: Record<string, unknown>[];",
	"  readonly bytecode: string;",
	"}",
	"",
];

const names = [];

for (const file of files) {
	const raw = JSON.parse(readFileSync(join(artifactsDir, file), "utf-8"));
	const name = basename(file, ".json");
	// camelCase identifier for export
	const ident = name.replace(/[^a-zA-Z0-9]/g, "_");
	names.push({ name, ident });

	lines.push(`export const ${ident}: ContractArtifact = {`);
	lines.push(`  contractName: ${JSON.stringify(raw.contractName ?? name)},`);
	lines.push(`  abi: ${JSON.stringify(raw.abi)},`);
	lines.push(`  bytecode: ${JSON.stringify(raw.bytecode)},`);
	lines.push(`} as const;`);
	lines.push("");
}

// Lookup map
lines.push("/** All contract artifacts keyed by name (for dynamic lookup). */");
lines.push("export const artifacts: Record<string, ContractArtifact> = {");
for (const { name, ident } of names) {
	lines.push(`  ${JSON.stringify(name)}: ${ident},`);
}
lines.push("} as const;");
lines.push("");

writeFileSync(join(generatedDir, "artifacts.ts"), lines.join("\n"));
console.log(`✓  Generated artifacts.ts (${names.length} contracts)`);

// ── Init code hash ─────────────────────────────────────────────────────────

// Read _hash-info.json and _init-code-hash.json if they exist
const initCodeHashLines = [
	"// Auto-generated by scripts/codegen.mjs — DO NOT EDIT",
	"",
];

try {
	const hashInfo = JSON.parse(
		readFileSync(join(artifactsDir, "_hash-info.json"), "utf-8"),
	);
	initCodeHashLines.push(
		`export const _hash_info = ${JSON.stringify(hashInfo)} as const;`,
	);
	initCodeHashLines.push("");
} catch {
	/* no hash info */
}

try {
	const initHash = JSON.parse(
		readFileSync(join(artifactsDir, "_init-code-hash.json"), "utf-8"),
	);
	initCodeHashLines.push(
		`export const _init_code_hash = ${JSON.stringify(initHash)} as const;`,
	);
	initCodeHashLines.push("");
} catch {
	// Compute from UniswapV2Pair bytecode if available
	try {
		const pair = JSON.parse(
			readFileSync(join(artifactsDir, "UniswapV2Pair.json"), "utf-8"),
		);
		// Import viem's keccak256 dynamically
		const { keccak256 } = await import("viem");
		const computed = keccak256(pair.bytecode);
		initCodeHashLines.push(`export const _init_code_hash = {`);
		initCodeHashLines.push(`  computed: ${JSON.stringify(computed)},`);
		initCodeHashLines.push(
			`  canonical: "0x96e8ac4277198ff8b6f785478aa9a39f403cb768dd02cbee326c3e7da348845f",`,
		);
		initCodeHashLines.push(`} as const;`);
		initCodeHashLines.push("");
	} catch (err) {
		console.warn("⚠  Could not compute init code hash:", err.message);
		initCodeHashLines.push(
			`export const _init_code_hash = { computed: "", canonical: "" } as const;`,
		);
		initCodeHashLines.push("");
	}
}

writeFileSync(
	join(generatedDir, "init-code-hash.ts"),
	initCodeHashLines.join("\n"),
);
console.log("✓  Generated init-code-hash.ts");

// ── Barrel export ──────────────────────────────────────────────────────────

const barrel = [
	"// Auto-generated by scripts/codegen.mjs — DO NOT EDIT",
	"export * from './artifacts.js';",
	"export * from './init-code-hash.js';",
	"",
].join("\n");

writeFileSync(join(generatedDir, "index.ts"), barrel);
console.log("✓  Generated index.ts");
